### ISSUE TITLE
Transfer of Knowledge

### ISSUE THREAD

**Issue by Accelsnow** [uoft-tapp/tapp#542]

**Comment by Altair59** [comment]
Readme or Wiki may add the following hints or contribution guidelines:

- ~~Remember to run `npm install` on local whenever the project's dependencies are updated~~ **mention this on Wiki**
- [x]  Add **[WIP]** tag in any PRs that you are currently working on but not yet finished
- [x]  Remember to assign yourself to any Issues you are interested to work on to let others know
- [x]  On Windows since symbolic liks do not work, any docker commands should run with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml` plus the command itself, for example `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up`
- [x]  You can skip certain test cases by using `it.skip`  or `describe.skip` to skip the entire section functionality from Jest library 
- [x]  Do not manually edit the contents of any snapshot files in `frontend\src\tests\__snapshots__`, since these snapshots are automatically generated and compared whenever `frontend npm test` runs
- [x]  Sometimes Travis CI may fail due to high loads of tasks, in this case you can just wait for all previous tasks to finish and push again to trigger another run for your changes

**Comment by frankcbw** [comment]
- Use `git stash` and `git stash apply` wisely can save much time and unnecessary commits
- Remember to `git fetch upstream master` and then `git merge upstream/master` frequently

**Comment by Accelsnow** [comment]
- It is required to run `docker-compose build` after you pull a branch with dependency updates. After that, you need to wipe the `pg_data` folder under the project directory and redo `docker-compose run backend rake db:setup` and `docker-compose run backend rake db:migrate`.
- If you would like code lint features in your IDE locally (not inside the docker), you need to run `npm install` in both the project directory and the frontend directory. The backend ruby's gemfile specifies a certain ruby version; therefore, it is required that the corresponding ruby version is installed on your PC in order to run `bundle install` and use rubocop properly.
- The tapp application contains several components that are assigned to certain ports. If those ports are occupied by other applications in your OS, you need to shut down those applications first. There will be an error message indicating this when you run `docker-compose up`.
- If you run the frontend tests through `docker-compose run frontend npm test` and found that all or most actual API tests have failed while the mock API tests have passed, it is likely a database error. Try resetting the database.
- The docker logs are very useful when debugging. Always check for error log messages when tests failed.
- If you do not have percommit hook setup, remember to run all the linting tests in the `tests/` directory.
- The `puts` statement in ruby will display its output in the backend docker stdout, the `console.log` statement in the frontend js/ts will display its output in the docker console and the terminal where you run `docker-compose run frontend npm test`.

**Comment by Altair59** [comment]
maybe someone experienced can talk about the performance test thing used when testing frontend components like `react table`

**Comment by osamaramihafez** [comment]
- You can use the endpoint ```api/v1/debug/routes``` to see a list of all recognized endpoints within the Ruby on Rails API.
- When creating tests, remember that your test will run against both the actual API and the Mock API unless the Mock API is not implemented (i.e. for mailing).
- When querying with ruby code, remember to use the active record framework instead of manually creating your own SQL queries
- Before working on a task, see how familiar you are with the environment (i.e. Do you have experience with Ruby on Rails? Probably not. This means you'll need some time to learn it! Punctuation: intended)
- When testing email formats, use mailcatcher. Note that running the tests clears the mailcatcher messages before and after it runs, so every time you want to check if an email is formatted correctly, use something like Postman to send the email and see the output. Also, you can see a list of all previous messages by accessing ```{instanceURL}:1080/messages``` (i.e. ```localhost:1080/messages```).
- Going over the already implemented tests gives you a better feel for how the endpoints are supposed to function if you're confused by or not sure of the swagger UI descriptions.

**Comment by frankcbw** [comment]
> maybe someone experienced can talk about the performance test thing used when testing frontend components like `react table`

Good Point. I will do that!
