### ISSUE TITLE
[Frontend UI] Contract template and Position tables to be reinitialized after deleting sessions

### ISSUE THREAD

**Issue by frankcbw** [uoft-tapp/tapp#564]
Both contract template and position tables need to be reinitialized with Redux after deleting a session. (Currently, it requires manually refreshing the page)

**Comment by alex-kozin** [comment]
Can reproduce, will try to tackle this one! @siefkenj

**Comment by alex-kozin** [comment]
I see the problem is a little bit wider than mentioned, currently, when we delete a session we have as selected, we don't update the selected session.
![image](https://user-images.githubusercontent.com/23097023/123510953-6ed14880-d64c-11eb-8cd6-4aed6de0a4d4.png)

One solution would be to either deselect a session or try to fallback on an existing one if it exists, triggering a re-fetch of all related info as if the user selected that session themselves.

From a user experience standpoint, both can be confusing, but selecting a random existing session seems more confusing - I would not expect a deletion to result in the info I might have never seen before being shown. So I would probably just clear most of the state related to the deleted session. Any thoughts on this @siefkenj ?

**Comment by siefkenj** [comment]
The best thing would be to fall back to a null `active_session`.
